on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  launcher:
    runs-on: ubuntu-latest
    steps:
      - name: Command Dispatch
        uses: peter-evans/slash-command-dispatch@13bc09769d122a64f75aa5037256f6f2d78be8c4 # v4.0.0
        with:
          token: ${{ secrets.token }}
          reaction-token: ${{ secrets.token }}
          permission: write
          issue-type: pull-request
          commands: |-
            rebase
            update-prep
